version: '3'
services:
  redis:
    image: redis:alpine
    container_name: "redis"
    ports:
      - "6384:6379"
    volumes:
      - ./data:/data
      - ./redis.conf:/redis.conf
    command: ["redis-server", "/redis.conf"]
